command_timeout = 1000

[cmd_duration]
disabled = true

[character]
# use_symbol_for_status = true
success_symbol = "[λ](bold #FC0FC0)"
error_symbol = "[✘](red)"
vicmd_symbol = "[V](bold green)"

[username]
style_user = "purple"
style_root = "red bold"
format = "[$user]($style)"
disabled = false
# show_always = true

[hostname]
ssh_only = true
format =  "[@$hostname](purple) "
disabled = false

[package]
display_private = true

[python]
python_binary = ["python3"]

[battery]
disabled = true


