notARepository: 'skip'
gui:
  editCommand: 'nvim'
  editCommandTemplate: '{{editor}} +{{line}} -- {{filename}}'
  mouseEvents: false
  showFileTree: true
  showIcons: true
  theme:
    selectedLineBgColor:
      - default
    selectedRangeBgColor:
      - default
    cherryPickedCommitBgColor:
      - reverse
    cherryPickedCommitFgColor:
      - reverse
keybinding:
  universal:
    prevPage: '<c-u>' # go to next page in list
    nextPage: '<c-d>' # go to previous page in list
git:
  paging:
    colorArg: always
    pager: delta --paging=never
