notARepository: 'skip'
gui:
  mouseEvents: true
  showFileTree: true
  showIcons: false
keybinding:
  universal:
    prevPage: '<c-u>' # go to next page in list
    nextPage: '<c-d>' # go to previous page in list
os:
  editPreset: 'nvim'
  open: '/opt/homebrew/bin/code {{filename}}'
  openDirInEditor: '/opt/homebrew/bin/code {{dir}}'
git:
  paging:
    colorArg: always
    pager: /opt/homebrew/bin/delta --paging=never
