source $HOME/.zsh/zinit.zsh
source $HOME/.zsh/plugins.zsh
source $HOME/.zsh/fzf.zsh
source $HOME/.zsh/zsh_alias.zsh

eval "$(starship init zsh)"

export PATH=$PATH:/home/tom/.local/bin
export MANPAGER="sh -c 'col -bx | batcat -l man -p'"
export PAGER=less
export EDITOR=nvim
ZSH_THEME="spaceship"

if command -v tmux &> /dev/null && [ -n "$PS1" ] && [[ ! "$TERM" =~ screen ]] && [[ ! "$TERM" =~ tmux ]] && [ -z "$TMUX" ]; then
	  exec tmux attach
fi
cd
