source $HOME/.zsh/zinit.zsh
source $HOME/.zsh/plugins.zsh
source $HOME/.zsh/zsh_alias.zsh

eval "$(starship init zsh)"

export PATH=$PATH:$HOME/.local/bin:/opt/apache-maven-3.6.3/bin:$HOME/.emacs.d/bin
export MANPAGER="sh -c 'col -bx | batcat -l man -p'"
export PAGER=less
export EDITOR=nvim
export VIMRC=$HOME/.config/nvim/init.vim
export DISPLAY=:0
# export TERM='xterm-256color'

if command -v tmux &> /dev/null && [ -n "$PS1" ] && [[ ! "$TERM" =~ screen ]] && [[ ! "$TERM" =~ tmux ]] && [ -z "$TMUX" ]; then
	  exec tmux attach
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export LIBGL_ALWAYS_INDIRECT=1

export JAR=/usr/lib/jvm/eclipse.jdt.ls/org.eclipse.jdt.ls.product/target/repository/plugins/org.eclipse.equinox.launcher_1.6.0.v20200915-1508.jar
export GRADLE_HOME=/usr/share/gradle
export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
export JDTLS_CONFIG=/usr/lib/jvm/eclipse.jdt.ls/org.eclipse.jdt.ls.product/target/repository/config_linux
export WORKSPACE=$HOME/projects
